---
title: "Google reviews"
author: "Slučajni šumari"
date: '02 05 2020 '
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(corrplot)
library(ggplot2)
library(reshape2)
library(GGally)
library(ggraph)
library(igraph)
library(ggExtra)
knitr::opts_chunk$set(echo = TRUE)
```

# Učitavanje podataka i deskriptivna statistika

```{r readdata}
df <- read_csv("data.csv")
```
```{r}
df[df < 1] <- NA
head(df)
glimpse(df)
summary(df)
df
```


```{r fig.width=20, fig.height=28}
ggplot(melt(df), aes(x="", y=value)) +
  geom_boxplot() +
  facet_wrap(~variable, ncol = 4, nrow = 6) +
  theme(strip.text.x = element_text(size = 20, face = "bold"))
```
```{r}
corr <- cor(df[-1], use="pairwise.complete.obs")
```

```{r fig.height = 12, fig.width = 12}
ggplot(melt(df), aes(x = value)) + 
  geom_histogram(breaks = seq(1, 5, 1)) +
  facet_wrap(~variable, ncol = 4, nrow = 6)
```

```{r fig.height = 20, fig.width=20}
col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
corrplot(corr, method = "color", col = col(200), addCoef.col = "black", order = "FPC")

```
```{r}
corr %>%
  as.data.frame() %>%
  mutate(var1 = rownames(.)) %>%
  gather(var2, value, -var1) %>%
  arrange(desc(value)) %>%
  group_by(value) %>%
  dplyr::filter(row_number()==1 & var1 != var2) -> corrs
```

```{r}
corrs %>% graph_from_data_frame -> corrs_graph
```
```{r fig.height = 8, fig.width = 8}
ggraph(corrs_graph, "linear", circular = T) + 
    geom_edge_arc2(aes(edge_alpha = value^4, edge_width = abs(value), color = value)) +
    geom_node_point(size = 2) +
    geom_node_text(aes(label = name), vjust = -1, hjust = 0) + guides(edge_alpha = "none", edge_width = "none") +
  scale_edge_colour_gradientn(limits = c(-1, 1), colors = c("firebrick2", "dodgerblue2")) + theme_void() 
```
```{r}
plt <- ggplot(df, aes(x = gyms, y = `swimming pools`)) + geom_point()
ggMarginal(plt, type = "boxplot", col="red")


```
```{r}
p=ggplot(df, aes(`swimming pools`, gyms, col="red")) +
ggtitle("Coolness depending on number of friends") +
geom_point() +
theme(legend.position=c(0.13, 0.87),
plot.title = element_text(hjust=0.5, size=12, face="bold"))
ggMarginal(p, type="boxplot", col="red")

```
```{r}
data <- melt(df[c("parks", "theatres")])
ggplot(data, aes(x=value, fill=variable)) + geom_density(alpha=0.25)
ggplot(data,aes(x=value, fill=variable)) + geom_histogram(alpha=0.25)
ggplot(data,aes(x=variable, y=value, fill=variable)) + geom_boxplot()
t.test(df$parks, df$theatres, conf.level = 0.95)
var.test(df$parks, df$theatres, conf.level = 0.95)
```


```{r}
data <- melt(df[c("gyms", "swimming pools")])
ggplot(data, aes(x=value, fill=variable)) + geom_density(alpha=0.25)
ggplot(data,aes(x=value, fill=variable)) + geom_histogram(alpha=0.25)
ggplot(data,aes(x=variable, y=value, fill=variable)) + geom_boxplot()

t.test(df$gyms, df$`swimming pools`)


```
```{r}
data <- melt(df[c("pubs/bars", "zoo")])
ggplot(data, aes(x=value, fill=variable)) + geom_density(alpha=0.25)
ggplot(data,aes(x=value, fill=variable)) + geom_histogram(alpha=0.25)
ggplot(data,aes(x=variable, y=value, fill=variable)) + geom_boxplot()

t.test(df$`pubs/bars`, df$zoo)
```


